---
sudo: required
dist: xenial

language: generic

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt install zip -y
  - sudo apt install awscli -y

script:
  # Get Packer, unzip and Validate
  - cd packer
  - wget https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip
  - unzip packer_1.3.3_linux_amd64.zip
  - packer validate -var-file=variables.sample.json php.json